import { mkdir, mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { MemoryStore } from "@open-maintainer/db";
import type { ContextPrPublishInput } from "@open-maintainer/github";
import type { GeneratedArtifact } from "@open-maintainer/shared";
import { describe, expect, it } from "vitest";
import {
  type ContextPrCommandRunner,
  createDashboardContextPrService,
  createLocalGhContextPrPublisher,
} from "../src/context-pr-service";
import { createRepositorySourceLifecycle } from "../src/repository-source-analysis";

describe("dashboard context PR service", () => {
  it("opens registered repo context PRs through a narrow service boundary", async () => {
    const store = new MemoryStore();
    const repositorySources = createRepositorySourceLifecycle({ store });
    const registered = await repositorySources.register({
      kind: "uploaded-files",
      name: "context-tool",
      files: [
        {
          path: "package.json",
          content: JSON.stringify({
            name: "context-tool",
            scripts: { test: "bun test" },
          }),
        },
      ],
    });
    expect(registered.ok).toBe(true);
    if (!registered.ok) {
      return;
    }
    const analysis = await repositorySources.prepare({
      repoId: registered.value.repo.id,
      intent: { kind: "analyze", profile: "refresh" },
    });
    expect(analysis.ok).toBe(true);
    if (!analysis.ok) {
      return;
    }
    store.artifacts.set(registered.value.repo.id, [
      artifact("repo_profile", 1, "{}"),
      artifact("AGENTS.md", 2, "# generated by open-maintainer\n"),
      artifact(
        ".open-maintainer.yml",
        3,
        "generated:\n  by: open-maintainer\n",
      ),
    ]);
    const service = createDashboardContextPrService({
      store,
      repositorySources,
      localPublisher: {
        async publish(input) {
          expect(input.repo.repoId).toBe(registered.value.repo.id);
          expect(input.writableArtifacts.map((item) => item.path)).toEqual([
            "AGENTS.md",
            ".open-maintainer.yml",
          ]);
          expect(input.body).toContain("Dashboard run:");
          return {
            id: "context_pr_test",
            repoId: input.repo.repoId,
            branchName: input.branchName,
            commitSha: "commit-sha",
            prNumber: 42,
            prUrl: "https://github.com/local/context-tool/pull/42",
            artifactVersions: input.writableArtifacts.map(
              ({ artifact }) => artifact.version,
            ),
            status: "succeeded",
            createdAt: "2026-04-30T00:00:00.000Z",
          };
        },
      },
    });

    const result = await service.open({ repoId: registered.value.repo.id });

    expect(result.ok).toBe(true);
    if (!result.ok) {
      return;
    }
    expect(result.contextPr.prUrl).toBe(
      "https://github.com/local/context-tool/pull/42",
    );
    expect(result.run?.status).toBe("succeeded");
    expect(result.run?.artifactVersions).toEqual([2, 3]);
    expect(store.contextPrs.get("context_pr_test")?.prNumber).toBe(42);
  });

  it("publishes local worktree context PRs through injectable git and gh ports", async () => {
    const repoRoot = await mkdtemp(path.join(tmpdir(), "context-pr-port-"));
    const commands: Array<{
      tool: "git" | "gh";
      args: string[];
      env?: Record<string, string>;
    }> = [];
    const runCommand: ContextPrCommandRunner = async (input) => {
      commands.push({
        tool: input.tool,
        args: input.args,
        ...(input.env ? { env: input.env } : {}),
      });
      if (
        input.tool === "git" &&
        input.args.join(" ") === "branch --show-current"
      ) {
        return "feature/context-base\n";
      }
      if (
        input.tool === "git" &&
        input.args.join(" ") === "diff --cached --quiet"
      ) {
        throw new Error("staged changes");
      }
      if (input.tool === "git" && input.args.join(" ") === "rev-parse HEAD") {
        return "commit-sha\n";
      }
      if (
        input.tool === "gh" &&
        input.args[0] === "pr" &&
        input.args[1] === "view"
      ) {
        throw new Error("no existing PR");
      }
      if (
        input.tool === "gh" &&
        input.args[0] === "pr" &&
        input.args[1] === "create"
      ) {
        return "https://github.com/local/context-tool/pull/44\n";
      }
      return "";
    };
    const publisher = createLocalGhContextPrPublisher({
      runCommand,
      clock: () => "2026-04-30T00:00:00.000Z",
      id: () => "context_pr_local",
    });

    try {
      await mkdir(path.join(repoRoot, ".open-maintainer"), {
        recursive: true,
      });
      const result = await publisher.publish(
        publishInput({
          repoRoot,
          artifact: artifact("AGENTS.md", 2, "# generated\n"),
        }),
      );

      expect(result).toEqual({
        id: "context_pr_local",
        repoId: "repo_1",
        branchName: "open-maintainer/context-1",
        commitSha: "commit-sha",
        prNumber: 44,
        prUrl: "https://github.com/local/context-tool/pull/44",
        artifactVersions: [2],
        status: "succeeded",
        createdAt: "2026-04-30T00:00:00.000Z",
      });
      await expect(
        readFile(path.join(repoRoot, "AGENTS.md"), "utf8"),
      ).resolves.toBe("# generated\n");
      expect(
        commands.map((command) => [command.tool, command.args]),
      ).toContainEqual([
        "git",
        ["checkout", "-B", "open-maintainer/context-1", "main"],
      ]);
      expect(
        commands.map((command) => [command.tool, command.args]),
      ).toContainEqual([
        "gh",
        [
          "pr",
          "create",
          "--base",
          "main",
          "--head",
          "open-maintainer/context-1",
          "--title",
          "Update context",
          "--body",
          "Body",
        ],
      ]);
      expect(commands.at(-1)).toEqual({
        tool: "git",
        args: ["checkout", "feature/context-base"],
      });
    } finally {
      await rm(repoRoot, { recursive: true, force: true });
    }
  });
});

function artifact(
  type: GeneratedArtifact["type"],
  version: number,
  content = "# generated by open-maintainer\n",
): GeneratedArtifact {
  return {
    id: `artifact_${version}`,
    repoId: "repo_1",
    type,
    version,
    content,
    sourceProfileVersion: 1,
    modelProvider: null,
    model: null,
    createdAt: "2026-04-30T00:00:00.000Z",
  };
}

function publishInput(input: {
  repoRoot: string;
  artifact: GeneratedArtifact;
}): ContextPrPublishInput {
  return {
    repo: {
      repoId: "repo_1",
      owner: "local",
      name: "context-tool",
      defaultBranch: "main",
      profileVersion: 1,
      worktreeRoot: input.repoRoot,
    },
    branchName: "open-maintainer/context-1",
    title: "Update context",
    body: "Body",
    writePolicy: "preserve-maintainer-owned",
    shouldOverwriteExistingFile: () => true,
    writableArtifacts: [
      { artifact: input.artifact, path: input.artifact.type },
    ],
    generatedAt: "2026-04-30T00:00:00.000Z",
    run: null,
  };
}
