import { execFile } from "node:child_process";
import {
  cp,
  mkdir,
  mkdtemp,
  readFile,
  rm,
  utimes,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { describe, expect, it } from "vitest";
import {
  codexGenerateArgs,
  createFakeCodexCli,
} from "./helpers/fake-model-cli";

const repoRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);
const fixtureRoot = path.join(repoRoot, "tests/fixtures/low-context-ts");
const execFileAsync = promisify(execFile);

async function runCli(args: string[], env: Record<string, string> = {}) {
  try {
    const { stdout, stderr } = await execFileAsync(
      "bun",
      ["apps/cli/src/index.ts", ...args],
      {
        cwd: repoRoot,
        env: { ...process.env, ...env },
      },
    );
    return { stdout, stderr, exitCode: 0 };
  } catch (error) {
    const result = error as {
      stdout?: string;
      stderr?: string;
      code?: number;
    };
    return {
      stdout: result.stdout ?? "",
      stderr: result.stderr ?? "",
      exitCode: result.code ?? 1,
    };
  }
}

describe("CLI doctor", () => {
  it("detects generated artifact drift from the current profile", async () => {
    const workdir = await mkdtemp(
      path.join(tmpdir(), "open-maintainer-doctor-"),
    );
    await cp(fixtureRoot, workdir, { recursive: true });
    const fakeCodex = await createFakeCodexCli();

    const generate = await runCli(
      [
        "generate",
        workdir,
        ...codexGenerateArgs,
        "--context",
        "codex",
        "--skills",
        "codex",
      ],
      fakeCodex.env,
    );
    expect(generate.exitCode).toBe(0);

    const packageJsonPath = path.join(workdir, "package.json");
    const packageJson = JSON.parse(await readFile(packageJsonPath, "utf8"));
    packageJson.scripts.typecheck = "tsc --noEmit";
    await writeFile(
      packageJsonPath,
      `${JSON.stringify(packageJson, null, 2)}\n`,
    );

    const doctor = await runCli(["doctor", workdir]);

    expect(doctor.exitCode).toBe(1);
    expect(doctor.stderr).toBe("");
    expect(doctor.stdout).toContain(
      'drift: command package.json script typecheck was added: "tsc --noEmit"',
    );
    expect(doctor.stdout).toContain(
      "drift: .open-maintainer/profile.json was generated from a different repository profile",
    );
    expect(doctor.stdout).toContain(`fix: bun run cli doctor ${workdir} --fix`);

    const fixed = await runCli(["doctor", workdir, "--fix"]);

    expect(fixed.exitCode).toBe(0);
    expect(fixed.stderr).toBe("");
    expect(fixed.stdout).toContain(
      "fix: refreshed .open-maintainer/profile.json and .open-maintainer/report.md",
    );
  });

  it("removes obsolete generated context artifacts with --fix", async () => {
    const workdir = await mkdtemp(
      path.join(tmpdir(), "open-maintainer-doctor-fix-"),
    );
    await cp(fixtureRoot, workdir, { recursive: true });
    const fakeCodex = await createFakeCodexCli();

    const generate = await runCli(
      [
        "generate",
        workdir,
        ...codexGenerateArgs,
        "--context",
        "codex",
        "--skills",
        "codex",
      ],
      fakeCodex.env,
    );
    expect(generate.exitCode).toBe(0);

    const obsoletePath = path.join(
      workdir,
      ".agents/skills/low-context-ts-obsolete/SKILL.md",
    );
    await mkdir(path.dirname(obsoletePath), { recursive: true });
    await writeFile(
      obsoletePath,
      [
        "---",
        "name: low-context-ts-obsolete",
        "description: Obsolete generated skill.",
        "---",
        "",
        "# Obsolete",
        "",
        "<!-- generated by open-maintainer; sourceProfileVersion=1; profileHash=old -->",
        "",
      ].join("\n"),
    );

    const doctor = await runCli(["doctor", workdir]);

    expect(doctor.exitCode).toBe(1);
    expect(doctor.stderr).toBe("");
    expect(doctor.stdout).toContain(
      "obsolete: .agents/skills/low-context-ts-obsolete/SKILL.md is a generated context artifact no longer tracked by .open-maintainer/profile.json",
    );
    expect(doctor.stdout).toContain(`fix: bun run cli doctor ${workdir} --fix`);

    const fixed = await runCli(["doctor", workdir, "--fix"]);

    expect(fixed.exitCode).toBe(0);
    expect(fixed.stderr).toBe("");
    expect(fixed.stdout).toContain(
      "remove: .agents/skills/low-context-ts-obsolete/SKILL.md",
    );
    expect(fixed.stdout).toContain("obsolete generated artifact");
    await expect(readFile(obsoletePath, "utf8")).rejects.toThrow();
  });

  it("removes expired local operational artifacts with --fix", async () => {
    const workdir = await mkdtemp(
      path.join(tmpdir(), "open-maintainer-doctor-retention-"),
    );
    await cp(fixtureRoot, workdir, { recursive: true });
    const fakeCodex = await createFakeCodexCli();

    const generate = await runCli(
      [
        "generate",
        workdir,
        ...codexGenerateArgs,
        "--context",
        "codex",
        "--skills",
        "codex",
      ],
      fakeCodex.env,
    );
    expect(generate.exitCode).toBe(0);

    const oldRunPath = path.join(
      workdir,
      ".open-maintainer/triage/runs/old.json",
    );
    const oldGeneratedReportPath = path.join(
      workdir,
      ".open-maintainer/report.md",
    );
    await mkdir(path.dirname(oldRunPath), { recursive: true });
    await writeFile(oldRunPath, '{"status":"old"}\n');
    const oldTime = new Date(Date.now() - 31 * 86_400_000);
    await utimes(oldRunPath, oldTime, oldTime);
    await utimes(oldGeneratedReportPath, oldTime, oldTime);

    const doctor = await runCli(["doctor", workdir]);

    expect(doctor.exitCode).toBe(1);
    expect(doctor.stderr).toBe("");
    expect(doctor.stdout).toContain(
      "retention: .open-maintainer/triage/runs/old.json is",
    );
    expect(doctor.stdout).toContain(
      "exceeding local artifact retention of 30 days",
    );
    expect(doctor.stdout).toContain(`fix: bun run cli doctor ${workdir} --fix`);

    const fixed = await runCli(["doctor", workdir, "--fix"]);

    expect(fixed.exitCode).toBe(0);
    expect(fixed.stderr).toBe("");
    expect(fixed.stdout).toContain(
      "remove: .open-maintainer/triage/runs/old.json",
    );
    expect(fixed.stdout).toContain("expired local operational artifact");
    await expect(readFile(oldRunPath, "utf8")).rejects.toThrow();
    await expect(readFile(oldGeneratedReportPath, "utf8")).resolves.toContain(
      "Open Maintainer",
    );
  });

  it("previews doctor fixes without removing generated artifacts", async () => {
    const workdir = await mkdtemp(
      path.join(tmpdir(), "open-maintainer-doctor-dry-run-"),
    );
    await cp(fixtureRoot, workdir, { recursive: true });
    const fakeCodex = await createFakeCodexCli();

    const generate = await runCli(
      [
        "generate",
        workdir,
        ...codexGenerateArgs,
        "--context",
        "codex",
        "--skills",
        "codex",
      ],
      fakeCodex.env,
    );
    expect(generate.exitCode).toBe(0);

    const obsoletePath = path.join(
      workdir,
      ".agents/skills/low-context-ts-obsolete/SKILL.md",
    );
    await mkdir(path.dirname(obsoletePath), { recursive: true });
    await writeFile(
      obsoletePath,
      [
        "---",
        "name: low-context-ts-obsolete",
        "description: Obsolete generated skill.",
        "---",
        "",
        "# Obsolete",
        "",
        "<!-- generated by open-maintainer; sourceProfileVersion=1; profileHash=old -->",
        "",
      ].join("\n"),
    );

    const doctor = await runCli(["doctor", workdir, "--fix", "--dry-run"]);

    expect(doctor.exitCode).toBe(1);
    expect(doctor.stderr).toBe("");
    expect(doctor.stdout).toContain("Open Maintainer doctor");
    expect(doctor.stdout).toContain("Mode: dry-run");
    expect(doctor.stdout).toContain("Doctor fix plan");
    expect(doctor.stdout).toContain(
      "remove: .agents/skills/low-context-ts-obsolete/SKILL.md",
    );
    expect(doctor.stdout).toContain("obsolete generated artifact");
    expect(doctor.stdout).not.toContain("| Action | Target");
    expect(doctor.stdout).toContain("Dry run: no doctor fixes applied.");
    await expect(readFile(obsoletePath, "utf8")).resolves.toContain(
      "Obsolete generated skill",
    );
  });

  it("names CI workflow drift from the stored profile", async () => {
    const workdir = await mkdtemp(
      path.join(tmpdir(), "open-maintainer-doctor-ci-"),
    );
    await cp(fixtureRoot, workdir, { recursive: true });
    const workflowDir = path.join(workdir, ".github/workflows");
    await mkdir(workflowDir, { recursive: true });
    await writeFile(
      path.join(workflowDir, "ci.yml"),
      "name: CI\non: [push]\njobs:\n  test:\n    runs-on: ubuntu-latest\n",
    );
    await writeFile(
      path.join(workflowDir, "lint.yml"),
      "name: Lint\non: [push]\njobs:\n  lint:\n    runs-on: ubuntu-latest\n",
    );
    const fakeCodex = await createFakeCodexCli();

    const generate = await runCli(
      [
        "generate",
        workdir,
        ...codexGenerateArgs,
        "--context",
        "codex",
        "--skills",
        "codex",
      ],
      fakeCodex.env,
    );
    expect(generate.exitCode).toBe(0);

    await writeFile(
      path.join(workflowDir, "ci.yml"),
      "name: CI\non: [push, pull_request]\njobs:\n  test:\n    runs-on: ubuntu-latest\n",
    );
    await rm(path.join(workflowDir, "lint.yml"));
    await writeFile(
      path.join(workflowDir, "release.yml"),
      "name: Release\non: [workflow_dispatch]\njobs:\n  build:\n    runs-on: ubuntu-latest\n",
    );

    const doctor = await runCli(["doctor", workdir]);

    expect(doctor.exitCode).toBe(1);
    expect(doctor.stderr).toBe("");
    expect(doctor.stdout).toContain(
      "drift: CI workflow .github/workflows/ci.yml was changed",
    );
    expect(doctor.stdout).toContain(
      "drift: CI workflow .github/workflows/lint.yml was removed",
    );
    expect(doctor.stdout).toContain(
      "drift: CI workflow .github/workflows/release.yml was added",
    );
    expect(doctor.stdout).toContain(
      "drift: .open-maintainer/profile.json was generated from a different repository profile",
    );
  });

  it("names docs, templates, and generated context artifact drift", async () => {
    const workdir = await mkdtemp(
      path.join(tmpdir(), "open-maintainer-doctor-docs-"),
    );
    await cp(fixtureRoot, workdir, { recursive: true });
    const templateDir = path.join(workdir, ".github/ISSUE_TEMPLATE");
    await mkdir(templateDir, { recursive: true });
    await writeFile(
      path.join(templateDir, "bug.yml"),
      "name: Bug report\ndescription: Report a reproducible bug.\n",
    );
    const fakeCodex = await createFakeCodexCli();

    const generate = await runCli(
      [
        "generate",
        workdir,
        ...codexGenerateArgs,
        "--context",
        "codex",
        "--skills",
        "codex",
      ],
      fakeCodex.env,
    );
    expect(generate.exitCode).toBe(0);

    await writeFile(
      path.join(workdir, "README.md"),
      "# Low Context TS\n\nUpdated setup guidance.\n",
    );
    await writeFile(
      path.join(templateDir, "bug.yml"),
      "name: Bug report\ndescription: Report a reproducible bug with logs.\n",
    );
    await writeFile(
      path.join(workdir, ".github/pull_request_template.md"),
      "## Validation\n\nList commands run.\n",
    );
    await writeFile(
      path.join(workdir, "AGENTS.md"),
      `${await readFile(path.join(workdir, "AGENTS.md"), "utf8")}\nManual local note.\n`,
    );

    const doctor = await runCli(["doctor", workdir]);

    expect(doctor.exitCode).toBe(1);
    expect(doctor.stderr).toBe("");
    expect(doctor.stdout).toContain(
      "drift: docs README.md was changed; review generated context against updated docs",
    );
    expect(doctor.stdout).toContain(
      "drift: template .github/ISSUE_TEMPLATE/bug.yml was changed; review issue and PR guidance",
    );
    expect(doctor.stdout).toContain(
      "drift: template .github/pull_request_template.md was added; review issue and PR guidance",
    );
    expect(doctor.stdout).toContain(
      "drift: context artifact AGENTS.md was changed; rerun generation or review the artifact",
    );
  });

  it("names lockfile, config, package boundary, and risk path drift", async () => {
    const workdir = await mkdtemp(
      path.join(tmpdir(), "open-maintainer-doctor-risk-"),
    );
    await cp(fixtureRoot, workdir, { recursive: true });
    const fakeCodex = await createFakeCodexCli();

    const generate = await runCli(
      [
        "generate",
        workdir,
        ...codexGenerateArgs,
        "--context",
        "codex",
        "--skills",
        "codex",
      ],
      fakeCodex.env,
    );
    expect(generate.exitCode).toBe(0);

    await writeFile(path.join(workdir, "tsconfig.json"), '{"strict":true}\n');
    await mkdir(path.join(workdir, "apps/admin"), { recursive: true });
    await writeFile(
      path.join(workdir, "apps/admin/package.json"),
      '{"scripts":{"test":"bun test"}}\n',
    );
    await writeFile(
      path.join(workdir, "src/security.ts"),
      "export const requiresReview = true;\n",
    );

    const doctor = await runCli(["doctor", workdir]);

    expect(doctor.exitCode).toBe(1);
    expect(doctor.stderr).toBe("");
    expect(doctor.stdout).toContain(
      "drift: lockfile/config tsconfig.json was changed; review setup and validation context",
    );
    expect(doctor.stdout).toContain(
      "drift: package boundary apps/admin was added; review package/app context",
    );
    expect(doctor.stdout).toContain(
      "drift: risk path src/security.ts was added; review high-risk area guidance",
    );
  });
});
